name: es

services:
  controller:
    privileged: true
    build: .
    devices:
      - /dev:/dev
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    ports:
      - 5000:5000
    restart: always